import { describe, expect, it } from "vitest";
import { analyzeSegments } from "../src/core/segments.js";
import fixtures from "./fixtures/twilio-parity.json";

// Parity against Twilio's reference message-segment-calculator
// (github.com/TwilioDevEd/message-segment-calculator). The fixtures were
// generated by running this corpus through the reference implementation and
// freezing its {encoding, segments} outputs — 126 cases covering GSM-7 and
// UCS-2 boundaries, extension characters, emoji/ZWJ content, and a
// deterministic fuzz sweep. If our packing ever disagrees with the
// reference, this suite names the exact body that diverged.

const ENCODING_MAP: Record<string, string> = { "GSM-7": "gsm7", "UCS-2": "ucs2" };

describe("Twilio reference calculator parity", () => {
  it("agrees on encoding and segment count for all frozen vectors", () => {
    expect(fixtures.length).toBeGreaterThanOrEqual(100);
    const disagreements: string[] = [];
    for (const { body, encoding, segments } of fixtures) {
      const r = analyzeSegments(body);
      if (r.encoding !== ENCODING_MAP[encoding] || r.segments !== segments) {
        disagreements.push(
          `${JSON.stringify(body.slice(0, 40))}… expected ${encoding}/${segments}, got ${r.encoding}/${r.segments}`,
        );
      }
    }
    expect(disagreements).toEqual([]);
  });
});
